version: "3"

services:
  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - C:\vlado\_docker_volumes\sonarqube\sonarqube_conf:/opt/sonarqube/conf
      - C:\vlado\_docker_volumes\sonarqube\sonarqube_data:/opt/sonarqube/data
      - C:\vlado\_docker_volumes\sonarqube\sonarqube_extensions:/opt/sonarqube/extensions
      - C:\vlado\_docker_volumes\sonarqube\sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - C:\vlado\_docker_volumes\sonarqube\postgresql:/var/lib/postgresql
      - C:\vlado\_docker_volumes\sonarqube\postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
