// Generated by CoffeeScript 1.4.0
var private_impl, ui;

private_impl = {
  _current_presentation_mode: "",
  presentation_mode: function() {
    var width;
    width = $("#presentation_mode").css("width");
    if (width === "150px") {
      return "mobile-portrait";
    } else if (width === "200px") {
      return "mobile-landscape";
    } else if (width === "250px") {
      return "desktop-wide";
    } else {
      return "";
    }
  },
  switch_presentation_mode: function() {
    var mode;
    mode = private_impl.presentation_mode();
    if (mode === private_impl._current_presentation_mode) {
      return;
    }
    private_impl._current_presentation_mode = mode;
    ui.navigation.deinit();
    ui.navigation = mode === "desktop-wide" ? private_impl.full_navigation : mode === "mobile-portrait" ? private_impl.collapsed_navigation : mode === "mobile-landscape" ? private_impl.collapsed_navigation : private_impl.no_navigation_mode;
    return ui.navigation.init();
  },
  common_init: function() {
    $('#navigation_menu_title').removeAttr("href");
    return $('.navigation_section_title').removeAttr("href");
  },
  full_navigation: {
    currently_shown_section: "",
    init: function() {
      private_impl.common_init();
      $('#page').hover(function() {
        var _base;
        return typeof (_base = ui.navigation).hide_menu === "function" ? _base.hide_menu() : void 0;
      });
      $('#navigation .navigation_section_title').each(function() {
        var section;
        section = $(this).attr('data-section-id');
        $(this).click(function() {
          var _base;
          return typeof (_base = ui.navigation).toggle_menu === "function" ? _base.toggle_menu(section) : void 0;
        });
        return $(this).hover(function() {
          var _base;
          return typeof (_base = ui.navigation).show_menu === "function" ? _base.show_menu(section) : void 0;
        });
      });
      return $(".navigation_section_items").css({
        'visibility': 'hidden',
        'display': 'block',
        'opacity': '0.0'
      });
    },
    deinit: function() {
      return $(".navigation_section_items").css({
        'visibility': 'visible',
        'display': 'block',
        'opacity': '1.0'
      });
    },
    show_menu: function(section) {
      var menu, title;
      if (section === private_impl.full_navigation.currently_shown_section) {
        return;
      }
      private_impl.full_navigation.hide_menu();
      title = ui.get_element("navigation_section_title__" + section);
      title.className = "navigation_section_title_active";
      menu = $("#navigation_section_items__" + section);
      menu.css({
        visibility: 'visible',
        z: '1'
      });
      menu.animate({
        opacity: '1.0'
      }, 200);
      return private_impl.full_navigation.currently_shown_section = section;
    },
    hide_menu: function() {
      var menu, section, title;
      if (private_impl.full_navigation.currently_shown_section === "") {
        return;
      }
      section = private_impl.full_navigation.currently_shown_section;
      title = ui.get_element("navigation_section_title__" + section);
      title.className = "navigation_section_title";
      menu = $("#navigation_section_items__" + section);
      menu.css({
        z: '0'
      });
      menu.animate({
        opacity: '0.0'
      }, 200, function() {
        return menu.css({
          visibility: 'hidden'
        });
      });
      return private_impl.full_navigation.currently_shown_section = "";
    },
    toggle_menu: function(section) {
      if (private_impl.full_navigation.currently_shown_section === "") {
        return private_impl.full_navigation.show_menu(section);
      } else {
        return private_impl.full_navigation.hide_menu();
      }
    }
  },
  collapsed_navigation: {
    init: function() {
      private_impl.common_init();
      $('#navigation .navigation_list').hide();
      $('#navigation .navigation_section_items').show();
      return $('#navigation_menu_title').click(function() {
        return $('#navigation .navigation_list').toggle();
      });
    },
    deinit: function() {
      $('#navigation .navigation_list').show();
      return $('#navigation_menu_title').off("click");
    }
  },
  no_navigation_mode: {
    init: function() {},
    deinit: function() {}
  }
};

ui = {
  get_element: function(_) {
    return document.getElementById(_);
  },
  navigation: private_impl.no_navigation_mode,
  init: function() {
    $(window).resize(function() {
      return private_impl.switch_presentation_mode();
    });
    return private_impl.switch_presentation_mode();
  }
};
