version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - C:\vlado\_docker_volumes\jenkins\jenkins_conf:/var/jenkins_home
      - C:\vlado\_docker_volumes\jenkins\docker_sock:/var/run/docker.sock
